//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SogetiSpain.MvvmCourse.WebServices.Client.EmployeeServiceClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeServiceClient.IEmployeeService")]
    public interface IEmployeeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetAll", ReplyAction="http://tempuri.org/IEmployeeService/GetAllResponse")]
        SogetiSpain.MvvmCourse.WebServices.EmployeeDto[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetAll", ReplyAction="http://tempuri.org/IEmployeeService/GetAllResponse")]
        System.Threading.Tasks.Task<SogetiSpain.MvvmCourse.WebServices.EmployeeDto[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetById", ReplyAction="http://tempuri.org/IEmployeeService/GetByIdResponse")]
        SogetiSpain.MvvmCourse.WebServices.EmployeeDto GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetById", ReplyAction="http://tempuri.org/IEmployeeService/GetByIdResponse")]
        System.Threading.Tasks.Task<SogetiSpain.MvvmCourse.WebServices.EmployeeDto> GetByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/Update", ReplyAction="http://tempuri.org/IEmployeeService/UpdateResponse")]
        bool Update(SogetiSpain.MvvmCourse.WebServices.EmployeeDto employeeDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/Update", ReplyAction="http://tempuri.org/IEmployeeService/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(SogetiSpain.MvvmCourse.WebServices.EmployeeDto employeeDto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeServiceChannel : SogetiSpain.MvvmCourse.WebServices.Client.EmployeeServiceClient.IEmployeeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServiceClient : System.ServiceModel.ClientBase<SogetiSpain.MvvmCourse.WebServices.Client.EmployeeServiceClient.IEmployeeService>, SogetiSpain.MvvmCourse.WebServices.Client.EmployeeServiceClient.IEmployeeService {
        
        public EmployeeServiceClient() {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SogetiSpain.MvvmCourse.WebServices.EmployeeDto[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<SogetiSpain.MvvmCourse.WebServices.EmployeeDto[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public SogetiSpain.MvvmCourse.WebServices.EmployeeDto GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<SogetiSpain.MvvmCourse.WebServices.EmployeeDto> GetByIdAsync(int id) {
            return base.Channel.GetByIdAsync(id);
        }
        
        public bool Update(SogetiSpain.MvvmCourse.WebServices.EmployeeDto employeeDto) {
            return base.Channel.Update(employeeDto);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(SogetiSpain.MvvmCourse.WebServices.EmployeeDto employeeDto) {
            return base.Channel.UpdateAsync(employeeDto);
        }
    }
}
