//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SogetiSpain.MvvmCourse.WebServices.Client.CustomerServiceClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerServiceClient.ICustomerService")]
    public interface ICustomerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetAll", ReplyAction="http://tempuri.org/ICustomerService/GetAllResponse")]
        SogetiSpain.MvvmCourse.WebServices.CustomerDto[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetAll", ReplyAction="http://tempuri.org/ICustomerService/GetAllResponse")]
        System.Threading.Tasks.Task<SogetiSpain.MvvmCourse.WebServices.CustomerDto[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetById", ReplyAction="http://tempuri.org/ICustomerService/GetByIdResponse")]
        SogetiSpain.MvvmCourse.WebServices.CustomerDto GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetById", ReplyAction="http://tempuri.org/ICustomerService/GetByIdResponse")]
        System.Threading.Tasks.Task<SogetiSpain.MvvmCourse.WebServices.CustomerDto> GetByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerServiceChannel : SogetiSpain.MvvmCourse.WebServices.Client.CustomerServiceClient.ICustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<SogetiSpain.MvvmCourse.WebServices.Client.CustomerServiceClient.ICustomerService>, SogetiSpain.MvvmCourse.WebServices.Client.CustomerServiceClient.ICustomerService {
        
        public CustomerServiceClient() {
        }
        
        public CustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SogetiSpain.MvvmCourse.WebServices.CustomerDto[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<SogetiSpain.MvvmCourse.WebServices.CustomerDto[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public SogetiSpain.MvvmCourse.WebServices.CustomerDto GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<SogetiSpain.MvvmCourse.WebServices.CustomerDto> GetByIdAsync(int id) {
            return base.Channel.GetByIdAsync(id);
        }
    }
}
